## NLP

Kodlara başlamadan önce yardım alacağımız bazı siteler ve kütüphaneler şunlardır.

https://www.nltk.org

https://www.w3schools.com/python/python_regex.asp#:~:text=A%20RegEx%2C%20or%20Regular%20Expression,contains%20the%20specified%20search%20pattern.



https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html




In [570]:
import numpy as np
import pandas as pd



In [571]:
yorumlar =pd.read_csv("C:/Users/yusuf/Desktop/GOALS/MACHINE LEARNING/Basic/datas/Restaurant_Reviews.csv",error_bad_lines=False)

yorumlar.head()

b'Skipping line 15: expected 2 fields, saw 4\nSkipping line 20: expected 2 fields, saw 3\nSkipping line 23: expected 2 fields, saw 3\nSkipping line 29: expected 2 fields, saw 3\nSkipping line 30: expected 2 fields, saw 3\nSkipping line 32: expected 2 fields, saw 4\nSkipping line 35: expected 2 fields, saw 3\nSkipping line 36: expected 2 fields, saw 3\nSkipping line 39: expected 2 fields, saw 3\nSkipping line 45: expected 2 fields, saw 3\nSkipping line 46: expected 2 fields, saw 3\nSkipping line 49: expected 2 fields, saw 3\nSkipping line 51: expected 2 fields, saw 3\nSkipping line 55: expected 2 fields, saw 3\nSkipping line 57: expected 2 fields, saw 4\nSkipping line 60: expected 2 fields, saw 3\nSkipping line 61: expected 2 fields, saw 3\nSkipping line 67: expected 2 fields, saw 3\nSkipping line 72: expected 2 fields, saw 3\nSkipping line 75: expected 2 fields, saw 3\nSkipping line 76: expected 2 fields, saw 4\nSkipping line 92: expected 2 fields, saw 3\nSkipping line 93: expected 2 f

Review  Liked
0                           Wow... Loved this place.    1.0
1                                 Crust is not good.    0.0
2          Not tasty and the texture was just nasty.    0.0
3  Stopped by during the late May bank holiday of...    1.0
4  The selection on the menu was great and so wer...    1.0

Kodları yazmadan önce bazı bilgileri vermek iyi olacaktır.

Yapmamız ilk gereken noktalama işaretlerinden kurtulmak olacaktır. Çünkü onları birleşik olarak alacak..


İkincisi ise Stop Words Case .. Yani and,the gibi kelimeleri belirlicez.. 


Üçüncü olarak da kelime vektörleri çıkarıcaz. Stop Words Case'e dikkatt..



substitution kelimesinden re.sub gelir. (ikamet, yer değiştirme) anlamlarına gelir.

Kullanımı: 

import re

#Replace all white-space characters with the digit "9":

txt = "The rain in Spain"
x = re.sub("\s", "9", txt)

The9rain9in9Spain olur

In [572]:
yorumlar['Review'][0]

'Wow... Loved this place.'

In [573]:
import re # Regular Expression kullanmak için..

yorum= re.sub('[^a-zA-Z]'," ", yorumlar['Review'][6]) #a-zA-Z olmayanları boşluk ile değiştir dedik..

Teker Teker yapabildikten sonra döngüye koymak kolay olacaktır.



In [574]:
yorum

'Honeslty it didn t taste THAT fresh  '

Büyük ve Küçük Harf Problemi

In [575]:
yorum= yorum.lower() 

yorum

'honeslty it didn t taste that fresh  '

Kelimeleri de listeye çevrilmesi

In [576]:
sozcukList=yorum.split()
sozcukList

['honeslty', 'it', 'didn', 't', 'taste', 'that', 'fresh']

STOP WORD CASE

Bizim işin anlamsal ve duygusallık kutupları üzerinde çalışıyoruz. O yüzden it,and,or,that gibi ifadeler bizim işimize maalesef ki yaramıyor.



Bunu yapmak için de NLTK kütüphanesinde yardım alacağız

In [577]:
#Döngü zamanı..

In [578]:

import re
import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

nltk.download('stopwords')
from nltk.corpus import stopwords

#Preprocessing (Önişleme)
derlem = []
for i in range(700):
    yorum = re.sub('[^a-zA-Z]',' ',yorumlar['Review'][i])
    yorum = yorum.lower()
    yorum = yorum.split()
    yorum = [ps.stem(kelime) for kelime in yorum if not kelime in set(stopwords.words('english'))]
    yorum = ' '.join(yorum)
    derlem.append(yorum)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\yusuf\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Bu eşsiz kelimeleri bir vektöre çevireceğimizi söylemiştik. Bunun için de aşağıdaki işlemi yapacağız.

In [579]:
# yorum=" ".join(yorum)

# yorum

Üstteki yazdıklarım karışık olabilir şayet asıl döngüdeki kısım önemli..

# Şuan Feature Engineering kısmındayız<p1>
## Şimdi defterimizde de yazdığı gibi Data Pre-processing kısmını bitirdik..<p2>


Feature Engineering'te yazdığımız KELİME SAYILARI ÜZERİNDEN GİDİCEZ! 

önemli bir parametremiz var 


max_features:
bu verilmezse tüm kelimeler(ram açısından baya sıkıntı bu durum.) için yapıyor ancak biz bir sayı verirsek ona göre sınırlama yapıyor.  

Sayının amacı en çok kullanılan 2000 tanesini al demek oluyor.

In [580]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=1000) #objemizi tanımladık..

x=cv.fit_transform(derlem).toarray() # x'i toarray ile diziye çevirdik. ve öncesinde de fit_transform ile hem istediğimiz şekle hem de veriyi öğretmiş olduk.

#Cümlelerimiz 0 ile 1'lere dönüştü..

In [581]:
yorumlar.iloc[:,-1] #bu da bizim y 'miz olacak.

0      1.0
1      0.0
2      0.0
3      1.0
4      1.0
      ... 
710    0.0
711    0.0
712    0.0
713    0.0
714    0.0
Name: Liked, Length: 715, dtype: float64

In [582]:

y=yorumlar.iloc[0:700,-1].values

#NAN VERİLER VAR DÜZELTELİM..
y[np.isnan(y)]=0

#NAN VERİLER VAR DÜZELTELİM..

# print(np.any(np.isnan(y)))
# y = np.nan_to_num(y)
# print(y)

ARTIK MAKİNE ÖĞRENMESİ Algoritmalarına giriyoruz buradan sonra.

In [583]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.37,random_state=42)

x_train


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

NAIVE BAYES 

In [584]:
from sklearn.naive_bayes import GaussianNB

gnb=GaussianNB()
gnb.fit(x_train,y_train)

y_pred= gnb.predict(x_test)



In [585]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,y_test)
cm

array([[ 62,  14],
       [ 66, 117]], dtype=int64)

In [586]:
#Başka sınıflandırma Algoritmaları da deneyebiliriz aslında.

DECISION TREE ile TAHMİN YAPILMASI

In [587]:
from sklearn.tree import DecisionTreeClassifier

dc_c= DecisionTreeClassifier(criterion="entropy") 

dc_c.fit(x_train,y_train)

dc_predict=dc_c.predict(x_test)


Confusion Matrix ile DECISION TREE

In [588]:
confusion_dc=confusion_matrix(y_test,dc_predict)

confusion_dc

array([[98, 30],
       [51, 80]], dtype=int64)

RANDOM FOREST İLE TAHMİN YAPMA

In [589]:
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(n_estimators=3,criterion="entropy") ##criterion ise bizim decision tree parametrelerinden biriydi,diğeri ise kaç tane decision tree çizeleceği olan (n_estimators=10)

rfc.fit(x_train,y_train)

rfc_y_predict =rfc.predict(x_test)

Confusion Matrix ile Random Forest

In [590]:
cm_rf=confusion_matrix(y_test,rfc_y_predict)

cm_rf

array([[85, 43],
       [50, 81]], dtype=int64)

SVM 

In [591]:
from sklearn.svm import SVC
svc= SVC(kernel='rbf') # yukarıdakidaki sitede değişik kernel'lerin olduğunu görebilirsiniz.
svc.fit(x_train,y_train)


y_pred_svc=svc.predict(x_test)


Confusion Matrix Support Vector Machine

In [592]:
cmForSvc=confusion_matrix(y_test,y_pred_svc)

cmForSvc

array([[96, 32],
       [45, 86]], dtype=int64)

KNN 

In [593]:
from sklearn.neighbors import KNeighborsClassifier


knn=KNeighborsClassifier(n_neighbors=3,metric="minkowski")

#Mesafesi, bir de kaç komşuya bakacağı bizim için önemli parametrelerdir.


knn.fit(x_train,y_train)

knn_y_predict= knn.predict(x_test)


In [594]:
from sklearn.metrics import confusion_matrix

knn_cm=confusion_matrix(y_test,knn_y_predict) #neyle neyin matrixi alıcam o da önemli..Tabii ki de tahminler arasında(y_pred,y_test)

knn_cm # ne kadar çok komşu olursa o kadar iyi sonuç verir algısı kırılmıştır. 1'deki sonuç 5'teki sonuçtan daha iyi sonuçlar vermiştir.


array([[99, 29],
       [51, 80]], dtype=int64)

## SIRASIYLA ALGORİTMALARIN SINIFLANDIRMADAKİ BAŞARI ORANI AŞAĞIDA VERİLMİŞTİR.

In [595]:
print(f'SVM ın Sınıflandırmadaki Başarı oranı {(96+86)/249} dur')
print(f'Random Forestın Sınıflandırmadaki Başarı oranı {(93+84)/249} dur')
print(f'Decision Treeın Sınıflandırmadaki Başarı oranı {(100+77)/249} dur')
print(f'Naive Bayesın Sınıflandırmadaki Başarı oranı {(117+62)/249} dur')
print(f'KNN ın Sınıflandırmadaki Başarı oranı {(99+88)/249} dur')

SVM ın Sınıflandırmadaki Başarı oranı 0.7309236947791165 dur
Random Forestın Sınıflandırmadaki Başarı oranı 0.7108433734939759 dur
Decision Treeın Sınıflandırmadaki Başarı oranı 0.7108433734939759 dur
Naive Bayesın Sınıflandırmadaki Başarı oranı 0.7188755020080321 dur
KNN ın Sınıflandırmadaki Başarı oranı 0.751004016064257 dur
