Kod'a başlamadan önce LDA ile ilgili, PCA ile karşılaştırmasını da yer alan güzel bir kaynak bırakıyorum. 

https://sebastianraschka.com/Articles/2015_pca_in_3_steps.html

PCA ile karşılaştırıcaz sonuçları o yüzden LDA ile bittiğinde PCA ile ilgili kodlarımızı da görebilirsiniz.


LDA kodları biraz aşağıda.


In [108]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [109]:
veriler=pd.read_csv("C:/Users/yusuf/Desktop/GOALS/MACHINE LEARNING/Basic/datas/Wine.csv")

veriler.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

X ve Y olarak ayırma

In [110]:
x=veriler.iloc[:,0:13]
y=veriler.iloc[:,-1:]

x

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  
0     3.92     1065  
1     3.40     1050  
2     3.17     1185  
3     3.45     1480  
4     2.93      735  
..     ...      ...  
173   1.74      740  
174   1.56      750  
175   1.56      835  
176   1.62      840  
177   1.60      560  

[178 rows x 13 columns]

eğitim ve test verieri olarak ayrılması.

In [111]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42) # Why fourty-two because The Hitchhiker's Guide to the Galaxy..

Ölçekleme 

In [112]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

## PCA 

PCA için daha detaylı parametreleri ve bilgileri  : 

https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

In [113]:
from sklearn.decomposition import PCA

pca= PCA(n_components=3) # burada bazı parametreler var. 

"""
n_compontens= kaç tane özellik(kolon) olacağına karar veriyoruz.Boyutumuza karar veriyoruz.
"""
pca_x_train= pca.fit_transform(x_train) # hem öğretip hem de uygulucak veri üzerinde. bunu yukarıda gösterdiğimiz algoritma üzerinde uygulıcak.

pca_x_train

#görüldüğü üzere x_train artık istediğimiz boyutta


#x_test ile x_train'in aynı boyutta olması için..

pca_x_test=pca.transform(x_test)



In [114]:
pca_x_test

array([[ 2.01965548, -1.12280932, -0.12214463],
       [ 1.08146849, -1.83197537,  0.20441044],
       [-2.67736386, -0.20426117,  0.76211757],
       [ 2.49457107, -1.17769938,  1.43144972],
       [ 0.23297494,  2.21075969, -1.22379687],
       [ 2.1482354 , -2.27506445,  1.03272081],
       [-0.42670823,  2.17852645, -0.70165038],
       [-2.55071452, -1.67494596,  0.29038799],
       [ 1.66033038,  1.58106029,  1.46918809],
       [-2.2286822 , -0.46730409, -0.83734505],
       [ 1.77412823,  0.33459487,  0.89529108],
       [-2.30584434, -2.15608089,  0.44975434],
       [ 0.66029565, -0.33482097, -0.79883021],
       [-2.34788933,  1.0638212 , -1.91858478],
       [ 2.24106704, -1.78344636,  0.47713277],
       [-0.21176437,  1.9558106 , -0.17148094],
       [-0.33346815,  2.33474311,  0.85815784],
       [-0.36292043,  2.46870563,  1.15478611],
       [ 2.68607021, -1.02755599, -0.86195616],
       [-0.40008704,  2.00699265,  1.22581771],
       [ 3.44141463, -2.77927643, -0.127

Artık bu veriler üzerinde bir makine öğrenmesi algoritması kullanabilir hale geldik.

Ben sırasıyla KNN-LogisticRegression kullanıcam.. Ve bunları Confusion Matrix ile ne kadar iyi sınıflandırdığına da bakıcam.



KNN 

Bi PCA'lı bir de PCA'sız(Gerçek ile karşılaştırıcaz.)

In [115]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3,metric="minkowski") #Mesafesi, bir de kaç komşuya bakacağı bizim için önemli parametrelerdir.



without PCA

In [116]:
knn.fit(x_train,y_train)

knn_y_predict= knn.predict(x_test)


c:\Users\yusuf\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


with PCA


In [117]:
knn2=KNeighborsClassifier(n_neighbors=3,metric="minkowski") #Mesafesi, bir de kaç komşuya bakacağı bizim için önemli parametrelerdir.


knn2.fit(pca_x_train,y_train)

knn2_y_predict=knn2.predict(pca_x_test)


c:\Users\yusuf\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Confusion Matrix for with PCA and without PCA , Before / After

Confusion Matrix without PCA

In [118]:
from sklearn.metrics import confusion_matrix

knn_cm=confusion_matrix(y_test,knn_y_predict)

knn_cm

array([[19,  0,  0],
       [ 1, 19,  1],
       [ 0,  0, 14]], dtype=int64)

Confusion Matrix with PCA

In [119]:
from sklearn.metrics import confusion_matrix

knn_cm2=confusion_matrix(y_test,knn2_y_predict)

knn_cm2

array([[19,  0,  0],
       [ 0, 21,  0],
       [ 0,  0, 14]], dtype=int64)

Before PCA / After PCA 

In [120]:
from sklearn.metrics import confusion_matrix

knn_cm3=confusion_matrix(knn_y_predict,knn2_y_predict)

knn_cm3

array([[19,  1,  0],
       [ 0, 19,  0],
       [ 0,  1, 14]], dtype=int64)

Linear Regression

In [121]:
from sklearn.linear_model import LogisticRegression

logistic_r1=LogisticRegression(random_state=0)

logistic_r1.fit(x_train,y_train)


c:\Users\yusuf\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(random_state=0)

In [122]:
y_pred_logistic=logistic_r1.predict(x_test) #x_test'leri tahmin et





Linear Regression for PCA

In [123]:
from sklearn.linear_model import LogisticRegression

logistic_r2=LogisticRegression(random_state=0)

logistic_r2.fit(pca_x_train,y_train)


y_pred_pca=logistic_r2.predict(pca_x_test)



c:\Users\yusuf\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Confusion Matrix for Linear Regression

without PCA

In [124]:
from sklearn.metrics import confusion_matrix

linear_cm=confusion_matrix(y_test,y_pred_logistic)

linear_cm

array([[19,  0,  0],
       [ 0, 20,  1],
       [ 0,  0, 14]], dtype=int64)

with PCA

In [125]:
from sklearn.metrics import confusion_matrix

linear_cm_pca=confusion_matrix(y_test,y_pred_pca)

linear_cm_pca

array([[17,  2,  0],
       [ 0, 21,  0],
       [ 0,  0, 14]], dtype=int64)

Before/After

In [126]:
from sklearn.metrics import confusion_matrix

linear_cm_match=confusion_matrix(y_pred_logistic,y_pred_pca)

linear_cm_match

array([[17,  2,  0],
       [ 0, 20,  0],
       [ 0,  1, 14]], dtype=int64)

## LDA 

In [127]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA 

lda = LDA(n_components=2) # n_components ile kaç boyuta ineceğine karar veriyoruz.

x_train_lda= lda.fit_transform(x_train,y_train) # PCA ile en önemli farklılıklarından birisi de bu. PCA'de sadece x_train veriyorduk . 
""""
Bunun sebebi teorik derste gördüğümüz gibi LDA'nın sınıfları da öğrenmesi ve görmesi gerektiğidir.

Akılda kalıcı not olması için:
PCA bu açıdan gözetimsiz(unsupervised) iken, LDA ise gözetimli (supervised)
özelliktedir. 

(clustering ve Classification farkı gibidir.)
"""


x_test_lda=lda.transform(x_test)


c:\Users\yusuf\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Şimdi makine öğrenmesine geçebilirim..

ben KNN'i kullanıcam.


KNN for LDA


In [128]:
classifier_lda=KNeighborsClassifier(n_neighbors=2,metric="minkowski") #4 komşuya gitsin diyoruz.
classifier_lda.fit(x_train_lda,y_train)

y_pred_lda=classifier_lda.predict(x_test_lda)




c:\Users\yusuf\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


Confusion Matrix for LDA 

In [129]:
from sklearn.metrics import confusion_matrix


lda_cm=confusion_matrix(y_pred_lda,y_test)

lda_cm

array([[19,  1,  0],
       [ 0, 20,  0],
       [ 0,  0, 14]], dtype=int64)