Amacımız bir müşteri bırakır mı bizim işletmeyi ? 

Eğer bunu anlayabilirsek, müşteriyi de kazanmış olucaz.

bu durumu anlamak..


In [67]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [68]:
veriler=pd.read_csv("C:/Users/yusuf/Desktop/GOALS/MACHINE LEARNING/Basic/datas/Churn_Modelling.csv")

veriler

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

Data-Preprocessing yapmadan önce bilinmesi gerekenler :

RowNumber gereksizdir. Çünkü 8 numaralı müşteri bizi bıraktı 11 numaralı bırakmadı gibi bir genelleme overfitting'e yol açar.


CustomerID sisteme herhangi bir etkiisi yok onu da kaldırıcaz.


Surname ise Lui olanlar bırakmıyor Tu olanlar bırakıyor gibi bir genelleme istemiyoruz. Bu kolondan da kurtulucaz.




## DATA PRE-PROCESSING 

X ve Y 'yi seçme..


In [69]:
x=veriler.iloc[:,3:13].values

y= veriler.iloc[:,-1:].values

x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [70]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int64)

ENCODING yapılması gereken kolonumuz var mı ? 

Evet.
Gender= Cinsiyet
Geography= Coğrafya.


Label Encoding yöntemini kullanıcam



In [71]:
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

# ilk ulkeler kolonunu alıcam.
# ulke=x[:,1]
# ulke
x[:,1]=le.fit_transform(x[:,1])
x[:,1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [72]:
#Sonra da cinsiyet için yapıcam.

le2=preprocessing.LabelEncoder() #aslında aynı kapsülde kullanabilir. Hiç bir sorun yok ancak buradaki amacımız kodun anlaşabilirliğini arttırmak.


# cinsiyet=x[:,2]
# cinsiyet
x[:,2]=le2.fit_transform(x[:,2])
x[:,2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

Şimdi biz artifical neural network(yapay sinir ağlarıyla) birlikte öğreneceğinden dolayı vereceğimiz features(özellikler) 0-1 arasında olmalı diğer kolonları ve buna uymayanlar için OneHotEncoder yöntemine de başvurucam. 

In [73]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer # aynı anda ayrı ayrı dönüştürülmesi için import ettik.


ohe=ColumnTransformer([("ohe",OneHotEncoder(dtype=float),[1])],remainder="passthrough") #parametreleri str olarak değişken, yöntem ve tipi, ve kaçıncı kolon olduğunu yazıyoruz.

x=ohe.fit_transform(x)
x=x[:,1:]

x

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

ColumnTransformer ile ilgili daha detaylı bilgiler için : 

https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html

DATA'NIN TEST VE TRAIN OLARAK AYRILMASI 


In [74]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42) # Why fourty-two because The Hitchhiker's Guide to the Galaxy..




Normalizasyon işlemleri

In [75]:
from sklearn.preprocessing import StandardScaler # bu scaler konusuna daha detaylı ileriki kodlarda geleceğiz.

sc=StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)


## YAPAY SİNİR AĞLARI 

In [76]:
import keras

from keras.models import Sequential
from keras.layers import Dense #Noronları oluşturabileceğimiz kapsül

In [77]:
classifier= Sequential() #bir model oluşturuyoruz.

classifier.add(Dense(11))
classifier.add(Dense(6,activation="relu"))      
                                                    #gizli katman
classifier.add(Dense(6,activation="relu"))

classifier.add(Dense(1,activation="sigmoid")) #çıkış katmanı


classifier.compile(loss='binary_crossentropy', optimizer='adam',metrics=["accuracy"])  #derlemiş olucaz bu şekilde.

#neden loss function binary_crossentropy olarak seçtik hep normal de categorical seçilir?
#TARGET KOLON hepsi 0 ila 1 arasında olduğu için, eğer başka şeyler de olsaydı onun için categorical kullanıcaz.



In [78]:
classifier.fit(x_train,y_train,epochs=55,batch_size=32)



Epoch 1/55
219/219 [==============================] - 1s 2ms/step - loss: 0.5170 - accuracy: 0.7861
Epoch 2/55
219/219 [==============================] - 0s 2ms/step - loss: 0.4520 - accuracy: 0.7936
Epoch 3/55
219/219 [==============================] - 0s 2ms/step - loss: 0.4372 - accuracy: 0.8003
Epoch 4/55
219/219 [==============================] - 0s 2ms/step - loss: 0.4294 - accuracy: 0.8084
Epoch 5/55
219/219 [==============================] - 0s 2ms/step - loss: 0.4228 - accuracy: 0.8116
Epoch 6/55
219/219 [==============================] - 0s 2ms/step - loss: 0.4120 - accuracy: 0.8243
Epoch 7/55
219/219 [==============================] - 0s 2ms/step - loss: 0.3901 - accuracy: 0.8393
Epoch 8/55
219/219 [==============================] - 0s 2ms/step - loss: 0.3696 - accuracy: 0.8483
Epoch 9/55
219/219 [==============================] - 0s 2ms/step - loss: 0.3577 - accuracy: 0.8550
Epoch 10/55
219/219 [==============================] - 0s 2ms/step - loss: 0.3525 - accuracy: 0.8554

In [79]:


y_pred=classifier.predict(x_test)

y_pred

array([[0.06034634],
       [0.01539269],
       [0.13660365],
       ...,
       [0.04374   ],
       [0.00449875],
       [0.1452654 ]], dtype=float32)

Birden veya 0'dan çok farklı rakamlardan oluşuyor bu şekilde Confusion koyamam. Bu rakamlar bu müşterilerin %80 bırakır %20 bırakır gibi ayrıştırmış..

Bundan dolayı bir eşikten geçirmek zorundayım.



In [83]:
y_pred=(y_pred>0.5)

y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

Confusion Matrix 'de doğruluğu kıyaslama..


In [82]:
from sklearn.metrics import confusion_matrix

cm= confusion_matrix(y_pred,y_test)

cm

array([[2345,  329],
       [  71,  255]], dtype=int64)