In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
veriler= pd.read_csv("C:/Users/yusuf/Desktop/GOALS/MACHINE LEARNING/Basic/kaynaklar/veriler.csv")

veriler.head()

ulke  boy  kilo  yas cinsiyet
0   tr  130    30   10        e
1   tr  125    36   11        e
2   tr  135    34   10        k
3   tr  133    30    9        k
4   tr  129    38   12        e

Data processing

In [3]:
x=veriler.iloc[:,1:4]

x

y=veriler.iloc[:,-1:]

y

cinsiyet
0         e
1         e
2         k
3         k
4         e
5         e
6         e
7         e
8         k
9         e
10        k
11        k
12        k
13        k
14        k
15        e
16        e
17        e
18        e
19        k
20        k
21        k

Datanın Test ve Train olarak ayrılması

In [4]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)


In [5]:
# ##Normalizasyon İşlemi 


# Normalizasyonun iki temel amacı vardır.
# 
# 
# 
#  Veri tabanında veri tekrarlarını ortadan kaldırmak ve veri tutarlılığını (doğruluğunu) artırmak. Normalizasyon, veri tabanlarına seviyelerle (normal formlar) uygulanır.


from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

x_test

array([[-1.75877619, -1.47845813, -1.53973273],
       [-0.17191045, -0.20745163,  0.94629407],
       [ 0.57193286, -0.16362382, -0.57739977],
       [-2.00672396, -1.21549127, -1.45953832],
       [ 0.4231642 ,  0.27465428,  1.42746055],
       [ 0.72070152,  1.15121048,  0.06415553],
       [-0.07273135,  0.09934304,  0.22454436]])

# Lojistik Regression

In [6]:
from sklearn.linear_model import LogisticRegression

logistic_r=LogisticRegression(random_state=0) #bir obje oluşturalım. Ve kütüphanesinde olan random_state parametresini ekliyorum

#eğitim kısmına gelelim..

logistic_r.fit(x_train,y_train) # x_train verilerinden y_train'i öğren.



c:\Users\yusuf\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(random_state=0)

Tahmin İşlemleri

In [7]:
y_pred=logistic_r.predict(x_test) #x_test'leri tahmin et


y_pred

array(['k', 'k', 'e', 'k', 'k', 'e', 'k'], dtype=object)

In [8]:
#şimdi bunları y_test ile karşılaştıralım..


y_test

cinsiyet
0         e
13        k
8         k
1         e
15        e
5         e
20        k

## Karmaşıklık Matrisi

In [9]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred) #neyle neyin matrixi alıcam o da önemli..Tabii ki de tahminler arasında(y_pred,y_test)

cm

array([[1, 3],
       [1, 2]], dtype=int64)

## KNN 

In [10]:
from sklearn.neighbors import KNeighborsClassifier


knn=KNeighborsClassifier(n_neighbors=1,metric="minkowski")

#Mesafesi, bir de kaç komşuya bakacağı bizim için önemli parametrelerdir.


knn.fit(x_train,y_train)

knn_y_predict= knn.predict(x_test)



c:\Users\yusuf\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [11]:
knn_y_predict

array(['k', 'k', 'k', 'e', 'k', 'e', 'k'], dtype=object)

In [12]:
y_test

cinsiyet
0         e
13        k
8         k
1         e
15        e
5         e
20        k

KNN için Confusion Matrix

# SVM 

Support Vector Machine


https://scikit-learn.org/stable/modules/svm.html

In [13]:
from sklearn.svm import SVC
svc= SVC(kernel='rbf') # yukarıdakidaki sitede değişik kernel'lerin olduğunu görebilirsiniz.
svc.fit(x_train,y_train)


y_pred_svc=svc.predict(x_test)




c:\Users\yusuf\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [14]:
cmForSvc=confusion_matrix(y_test,y_pred_svc)

cmForSvc

array([[1, 3],
       [0, 3]], dtype=int64)